### ISSUE TITLE
Command 'KarateIDE: Generate Karate Test' resulted in error (Cannot read property 'fspath' of undefined)

### ISSUE THREAD

**Issue by mcrobbj-abrdn** [ZenWave360/karate-ide#11]
There is nothing in the documentation that states how this should be defined. I get a failure for all the generators

**Comment by ivangsa** [comment]
KarateIDE Generators can  be executed on OpenAPI (yml format) files using right-click context on explorer

https://github.com/ZenWave360/karate-ide#generate-karate-tests-from-openapi-definitions

I think you are trying to launch the command from Command Palette, where no file specified...

I may consider adding a File Prompt when launched from Command Palette but I think most users will use the context menu

Let me know if it works for you..

**Comment by mcrobbj-abrdn** [comment]
My mistake, your suggestion works. Many thanks.
