### ISSUE TITLE
Add support for multi-root workspace

### ISSUE THREAD

**Issue by cheanwei** [ZenWave360/karate-ide#14]
When open the VS Code workspace with multi-roots, .feature files are not detected by Karate IDE and not code lens applied to .feature files

**Comment by ivangsa** [comment]
Hi @cheanwei 
muti-root workspaces are supported, 
you need to set the following setting `karateIDE.multimodule.rootModuleMarkerFile` to the name of a file that sits on the root of your modules, by default is pom.xml for maven, but if you are using other build tool just update as needed..

**Comment by cheanwei** [comment]
I am referring to this Visual Studio Code multi root workspace: https://code.visualstudio.com/docs/editor/multi-root-workspaces, not the submodules within single root project. In fact I am using Maven projects now.

**Comment by ivangsa** [comment]
OK, thanks for reporting this..
I'm adding this to the backlog

**Comment by ivangsa** [comment]
Hi @cheanwei 
this has been included in version 1.1.2

feel free to close this issue if it works for you

Regards
