### ISSUE TITLE
Feature requuest

### ISSUE THREAD

**Issue by mcrobbj** [ZenWave360/karate-ide#27]
Is there a away to add test templates, I would like to add some basic security testing to make sure code handles stuff like no access token, invalid token ( expired, invalid aud, issuer) etc, is there any means to do this?

**Comment by ivangsa** [comment]
hi @mcrobbj 

I'm afraid the way templates are loaded they can not be added or customized

Refactoring this VSCode extension to allow 'extending' the templates is not on my roadmap right now..

Threre is a chance I may migrate these karate templates to [ZenWave SDK](https://zenwave360.github.io/zenwave-sdk/)
there are code generators for `SpringTestClient` and `RestAssured` that can be extended and customized...

If you are willing to help creating and testing the sdk plugin, then open a feature request there... setting the initial base line should be quick..

(btw, it's written in Java and handlebars)
