### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by Mohitkrishna12** [ZenWave360/karate-ide#28]
Hi @ivangsa ,

I think it would be great if it is possible to pass 'args' as a parameter directly in `call read('classpath:karate-auth.js') args ` instead of passing it as 'args.auth'. So that in 'karate-auth.js' file we can write our own authentication logic with the help of other args. Like passing wrong access token based on the status code to get 404 error.

```
* def authHeader = call read('classpath:karate-auth.js') args.auth
* def headers = karate.merge(args.headers || {}, authHeader || {})
```
(Code snippet taken from the auto generated file).

**Comment by ivangsa** [comment]
Hi @Mohitkrishna12 

thanks for this idea, I'm all in favor of flexibility

I think you can already achieve that logic inside karate-auth.js:

- One option is to pass all the information you need inside auth object: 

```gherkin
* def auth = { username: '', password: '', otherinfo: '' }
```
- But if you preffer to get the info from other parts of `args` object you can do it inside karate-auth.js using `karate.get("any karate property")`

<img width="739" alt="image" src="https://github.com/ZenWave360/karate-ide/assets/1246876/f5dc885e-6aec-42c0-b1e1-a10633148488">

This works...

Let me know if this can solve your use case.

**Comment by Mohitkrishna12** [comment]
Thanks a lot @ivangsa `karate.get("any karate property")` works fine as I expected it helps.
